---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvert
  default_box: perk/ubuntu-2204-arm64
platforms:
  - name: Ubuntu
    memory: 512
    cpus: 1
provisioner:
  name: ansible
verifier:
  name: ansible
