# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# Author: Bradley Chatha

---
- name: Install
  hosts: all
  tasks:
    - name: Run role
      vars:
        v_platform: aws
        v_task: install
      ansible.builtin.include_role:
        name: ../ansible/golden_setup
