---
- name: Wait for connection
  hosts:
    - servers
    - clients
    - boundary_servers
    - boundary_clients
    - ingress
  gather_facts: false
  tasks:
    - name: Wait
      ansible.builtin.wait_for_connection:

- name: Clear old data
  hosts:
    - servers
    - clients
    - boundary_servers
    - boundary_clients
    - ingress
  tags: clear
  become: true
  tasks:
    - name: Stop Consul
      failed_when: false
      ansible.builtin.systemd:
        name: consul
        state: stopped
    - name: Clear Consul
      ansible.builtin.file:
        path: /opt/consul
        state: absent
    - name: Stop Nomad
      failed_when: false
      ansible.builtin.systemd:
        name: nomad
        state: stopped
    - name: Clear Nomad
      ansible.builtin.file:
        path: /opt/nomad
        state: absent
    - name: Clear Nomad token
      ansible.builtin.file:
        path: /tmp/nomad.token
        state: absent
    - name: Stop Boundary
      failed_when: false
      ansible.builtin.systemd:
        name: boundary
        state: stopped
    - name: Clear Boundary password
      ansible.builtin.file:
        path: /tmp/boundary.password
        state: absent

- name: Install
  tags: install
  hosts:
    - servers
    - clients
    - boundary_servers
    - boundary_clients
    - ingress
  tasks:
    - name: Run role
      vars:
        v_platform: aws
        v_task: install
      ansible.builtin.include_role:
        name: golden_setup

- name: Bootstrap External Services via Bastion
  tags: bootstrap_bastion
  hosts: bastion
  become: true
  tasks:
    - name: Ensure bastion has correct packages installed
      ansible.builtin.apt:
        name:
          - postgresql
          - pip
          - libpq-dev
        update_cache: true
    - name: Ensure bastion has psycopg2 installed
      ansible.builtin.pip:
        name:
          - psycopg2
    - name: Drop old database
      community.postgresql.postgresql_db:
        db: boundary
        login_host: "{{ f_postgres_host }}"
        login_user: "{{ f_postgres_username }}"
        login_password: "{{ f_postgres_password }}"
        port: "{{ f_postgres_port }}"
        state: absent
    - name: Bootstrap
      vars:
        v_platform: aws
        v_task: bootstrap_bastion
      ansible.builtin.include_role:
        name: golden_setup

- name: Bootstrap Boundary
  tags: bootstrap_boundary
  hosts: boundary_servers
  tasks:
    - name: Configure
      ansible.builtin.shell: |
        sudo bash /etc/bchatha/scripts/boundary_as_server.sh
        sudo bash /etc/bchatha/scripts/boundary_userdata.sh
    - name: Bootstrap
      vars:
        v_platform: aws
        v_task: bootstrap_boundary
      ansible.builtin.include_role:
        name: golden_setup

- name: Start Servers
  tags: start_servers
  hosts: servers
  tasks:
    - name: Start
      ansible.builtin.shell: |
        sudo bash /etc/bchatha/scripts/consul_as_server.sh
        sudo bash /etc/bchatha/scripts/nomad_as_server.sh
        sudo rm /tmp/consul.token.type

- name: Bootstrap Servers
  tags: bootstrap_servers
  hosts: servers
  tasks:
    - name: Bootstrap
      vars:
        v_platform: aws
        v_task: bootstrap
      ansible.builtin.include_role:
        name: golden_setup
    - name: Run userdata
      ansible.builtin.shell: |
        sudo bash /etc/bchatha/scripts/consul_userdata.sh
        sudo bash /etc/bchatha/scripts/nomad_userdata.sh

- name: Start Ingress
  tags: start_ingress
  hosts: ingress
  tasks:
    - name: Start
      ansible.builtin.shell: |
        sudo bash /etc/bchatha/scripts/consul_as_client.sh
        sudo bash /etc/bchatha/scripts/consul_userdata.sh
        sudo bash /etc/bchatha/scripts/traefik_userdata.sh

- name: Start Clients
  tags: start_clients
  hosts: clients
  tasks:
    - name: Start
      ansible.builtin.shell:
        cmd: |
          sudo bash /etc/bchatha/scripts/consul_as_client.sh
          sudo bash /etc/bchatha/scripts/nomad_as_client.sh
          sudo bash /etc/bchatha/scripts/consul_userdata.sh
          sudo bash /etc/bchatha/scripts/nomad_userdata.sh

- name: Start Boundary Clients
  tags: start_boundary_clients
  hosts: boundary_clients
  tasks:
    - name: Start
      ansible.builtin.shell:
        cmd: |
          sudo bash /etc/bchatha/scripts/boundary_as_client.sh
          sudo bash /etc/bchatha/scripts/boundary_userdata.sh

- name: Start Boundary Servers (again)
  tags: start_boundary_servers
  hosts: boundary_servers
  tasks:
    - name: Start
      ansible.builtin.shell:
        cmd: |
          sudo bash /etc/bchatha/scripts/boundary_as_server.sh
          sudo bash /etc/bchatha/scripts/consul_as_client.sh
          sudo bash /etc/bchatha/scripts/consul_userdata.sh
          sudo bash /etc/bchatha/scripts/boundary_userdata.sh
