---
- name: Render userdata script
  ansible.builtin.template:
    src: aws/boundary/boundary_userdata.bash.j2
    dest: /etc/bchatha/scripts/boundary_userdata.sh
    mode: u=rx
    owner: root
    group: root
